// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBIe27fD-lEmuTH4rIvzhXP7OIEzNgn3I',
    appId: '1:753650662723:web:35f511b1fb9487f69743f6',
    messagingSenderId: '753650662723',
    projectId: 'vendor-app-fuelit',
    authDomain: 'vendor-app-fuelit.firebaseapp.com',
    storageBucket: 'vendor-app-fuelit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQvs3ehMN3_t-CT4PI-dlIsAPT01tqHg',
    appId: '1:753650662723:android:6a44ca073c1d700b9743f6',
    messagingSenderId: '753650662723',
    projectId: 'vendor-app-fuelit',
    storageBucket: 'vendor-app-fuelit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEKpMasKJoVOU_0BPsrR08_lbGODPsiXk',
    appId: '1:753650662723:ios:5addd7797c9387a09743f6',
    messagingSenderId: '753650662723',
    projectId: 'vendor-app-fuelit',
    storageBucket: 'vendor-app-fuelit.appspot.com',
    iosBundleId: 'com.example.vendorapp.fuelItVendorApp',
  );
}
